"""Read-only installation gate: administrator-owned tree and protected ancestors.

The checksum manifest is generated by the administrator after offline installation.
This gate checks ownership/modes; sha256sum in ExecStartPre checks content separately.
Run with the trusted system interpreter, not the tree being checked.
"""
import os
from pathlib import Path
import stat
import sys


def immutable(path):
    info = path.stat()
    if info.st_uid != 0 or info.st_mode & 0o022:
        raise ValueError(f"administrator ownership and no group/other write required: {path}")
    if not (stat.S_ISREG(info.st_mode) or stat.S_ISDIR(info.st_mode)):
        raise ValueError(f"unexpected installation file type: {path}")


def check_path(path):
    # Check both lexical parents and symlink destination parents. Symlinks such
    # as venv/bin/python are legitimate only when their destinations are trusted.
    for candidate in (path.absolute(), path.resolve(strict=True)):
        immutable(candidate)
        for parent in candidate.parents:
            immutable(parent)


def verify(root, config):
    check_path(root)
    check_path(config)
    for base, directories, files in os.walk(root, followlinks=False):
        for name in directories + files:
            entry = Path(base) / name
            check_path(entry)
            if (entry.is_symlink() and entry.is_dir()
                    and not entry.resolve(strict=True).is_relative_to(root.resolve(strict=True))):
                raise ValueError(f"directory symlinks must stay inside the installation: {entry}")
            # Internal directory targets are also walked at their real location.
            # This allows the standard venv lib64 -> lib without skipping its files.


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: verify_install.py INSTALL_ROOT CONFIG")
    try:
        verify(Path(sys.argv[1]), Path(sys.argv[2]))
    except (OSError, ValueError) as error:
        raise SystemExit(str(error))
    print("installation ownership and modes verified (not an inter-UID probe)")
